### ISSUE TITLE
Make comparison plots have the same color axis scales

### ISSUE THREAD

**Issue by rosiealice** [NorESMhub/xesmf_clm_fates_diagnostic#6]
Where the values in the 1st and 2nd model runs for comparison are differnt enough to shift the axis limits, differences in the zxes limits between runs makes it harder to visually interrogate the patterns of differences and assess their significance. And the plots don't look as nice.  e.g. 
![n1850 FATES-SP ne30_tn14 alpha08d_AFparams 202412129_compare_n1850 FATES-SP ne30_tn14 alpha08d 20241209_ANN_FATES_GPP_0001-0004](https://github.com/user-attachments/assets/feb1edda-665f-401c-a6f8-b16587f312f8)

Maybe a scheme whereby wwe choose the wider axis limit in each case might work? I don't know if this would be super annoying to code up (e.g. if we are not remeber this info between plots) so it is not imperative but would just be a quality of life thing...

**Comment by maritsandstad** [comment]
Solved in commit b4baedb
